// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuBp1wIi1dYWGfIJ64itWEn1Mx5eGu_mE',
    appId: '1:858445286823:web:0b1d3fae95c5f444df3a82',
    messagingSenderId: '858445286823',
    projectId: 'login-demo-84bc1',
    authDomain: 'login-demo-84bc1.firebaseapp.com',
    storageBucket: 'login-demo-84bc1.appspot.com',
    measurementId: 'G-MRSF62J2DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCehDEgVzpdKGa3oX4CrzyNR2IbAWsyZWA',
    appId: '1:858445286823:android:3d20a759439b042fdf3a82',
    messagingSenderId: '858445286823',
    projectId: 'login-demo-84bc1',
    storageBucket: 'login-demo-84bc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx1QXothz8khvspp9xDtg0bHSxEOAe5hQ',
    appId: '1:858445286823:ios:843404ade6af05dfdf3a82',
    messagingSenderId: '858445286823',
    projectId: 'login-demo-84bc1',
    storageBucket: 'login-demo-84bc1.appspot.com',
    iosBundleId: 'com.example.fbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx1QXothz8khvspp9xDtg0bHSxEOAe5hQ',
    appId: '1:858445286823:ios:bc10bcf2d324a1afdf3a82',
    messagingSenderId: '858445286823',
    projectId: 'login-demo-84bc1',
    storageBucket: 'login-demo-84bc1.appspot.com',
    iosBundleId: 'com.example.fbApp.RunnerTests',
  );
}
